"""Your migration message

Revision ID: 1b3e1b6f6db3
Revises: f9410219744f
Create Date: 2025-01-13 03:21:00.248785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3e1b6f6db3'
down_revision = 'f9410219744f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the hotel table
    op.create_table('hotel',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('location', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('amenities', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Insert a default hotel with id = 1
    op.execute("""
        INSERT INTO hotel (id, name, location, description, rating, amenities, created_at, updated_at)
        VALUES (1, 'Default Hotel', 'Default Location', 'Default Description', 0.0, 'Default Amenities', NOW(), NOW())
    """)

    # Create the review table
    op.create_table('review',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('hotel_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.CheckConstraint('rating >= 1 AND rating <= 5', name='valid_rating'),
        sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Add the hotel_id column to the room table
    op.add_column('room', sa.Column('hotel_id', sa.Integer(), nullable=True))

    # Populate hotel_id with valid values (e.g., set it to 1 for all rows)
    op.execute("UPDATE room SET hotel_id = 1 WHERE hotel_id IS NULL")

    # Alter the column to make it NOT NULL
    op.alter_column('room', 'hotel_id', nullable=False)

    # Create a foreign key constraint
    op.create_foreign_key('fk_room_hotel', 'room', 'hotel', ['hotel_id'], ['id'])

    # Alter the description column type
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('fk_room_hotel', type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('hotel_id')

    op.drop_table('review')
    op.drop_table('hotel')
    # ### end Alembic commands ###